require 'fileutils'
require 'set'

# Configuration
SOURCE_DIR = 'Sources/Cryptonite/ASN1/Generated'
OUTPUT_FILE = 'Sources/Cryptonite/ASN1/CombinedGenerated.swift'

def compress_files
  unless Dir.exist?(SOURCE_DIR)
    puts "Error: Directory #{SOURCE_DIR} does not exist."
    exit 1
  end

  files = Dir.glob(File.join(SOURCE_DIR, '**', '*.swift')).sort
  if files.empty?
    puts "No Swift files found in #{SOURCE_DIR}"
    exit 0
  end

  puts "Found #{files.count} files to compress."

  imports = Set.new
  content_buffer = []

  # Commons imports we expect and want to strip from individual bodies if we put them at top
  # Assuming standard imports.
  
  files.each do |file_path|
    content = File.read(file_path)
    lines = content.lines

    file_content = []
    
    lines.each do |line|
      stripped = line.strip
      if stripped.start_with?('import ')
        imports.add(stripped)
      elsif stripped.start_with?('// Generated by') || stripped.start_with?('//') 
        # Skip top-level comments or specific headers if desired, 
        # but keeping comments is safer unless they are redundant headers.
        # Let's simple skip the "Generated by" header to avoid 800 reps.
        unless stripped.include?('Generated by ASN1.ERP.UNO')
             file_content << line
        end
      else
        file_content << line
      end
    end
    
    # Trim leading/trailing whitespace from the file block
    joined_content = file_content.join
    content_buffer << "// MARK: - #{File.basename(file_path)}\n" + joined_content.strip + "\n\n"
  end

  puts "Writing merged content to #{OUTPUT_FILE}..."

  File.open(OUTPUT_FILE, 'w') do |f|
    f.puts "// Consolidated ASN.1 Generated Files"
    f.puts "// Generated at #{Time.now}"
    f.puts
    
    # Write Imports
    imports.sort.each { |imp| f.puts imp }
    f.puts
    
    # Write Content
    content_buffer.each { |block| f.puts block }
  end

  puts "Successfully created #{OUTPUT_FILE}."
  
  # Remove the original directory
  puts "Removing original Generated directory..."
  FileUtils.rm_rf(SOURCE_DIR)
  puts "Done."
end

compress_files
